"""initial tables

Revision ID: 026606a4d6b7
Revises: 69863d1b8b05
Create Date: 2026-01-27 14:58:41.321877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026606a4d6b7'
down_revision: Union[str, Sequence[str], None] = '69863d1b8b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('withdrawal_pin', sa.String(), nullable=True))
    op.add_column('withdrawals', sa.Column('name', sa.String(), nullable=False))
    op.add_column('withdrawals', sa.Column('number', sa.String(), nullable=False))
    op.add_column('withdrawals', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('withdrawals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdrawals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('withdrawals', 'status')
    op.drop_column('withdrawals', 'number')
    op.drop_column('withdrawals', 'name')
    op.drop_column('users', 'withdrawal_pin')
    # ### end Alembic commands ###
