"""initial tables

Revision ID: 1fb9e310f21f
Revises: e319e66ef14f
Create Date: 2026-01-23 14:16:26.771445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb9e310f21f'
down_revision: Union[str, Sequence[str], None] = 'e319e66ef14f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=False))
    op.add_column('users', sa.Column('referred_by', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
