"""initial tables

Revision ID: 3fa2e7dc0710
Revises: 3ff19b29e6f1
Create Date: 2026-02-07 19:37:23.948065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa2e7dc0710'
down_revision: Union[str, Sequence[str], None] = '3ff19b29e6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('whatsapp_link', sa.String(), nullable=True),
    sa.Column('customer_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_contacts_id'), 'app_contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_contacts_id'), table_name='app_contacts')
    op.drop_table('app_contacts')
    # ### end Alembic commands ###
