"""initial tables

Revision ID: 3ff19b29e6f1
Revises: 66b10e21061c
Create Date: 2026-02-06 12:43:43.765299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff19b29e6f1'
down_revision: Union[str, Sequence[str], None] = '66b10e21061c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spin_wheel_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_spins_per_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spin_wheel_config_id'), 'spin_wheel_config', ['id'], unique=False)
    op.create_table('spin_wheel_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spin_wheel_rewards_id'), 'spin_wheel_rewards', ['id'], unique=False)
    op.create_table('user_spins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['spin_wheel_rewards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_spins_id'), 'user_spins', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_spins_id'), table_name='user_spins')
    op.drop_table('user_spins')
    op.drop_index(op.f('ix_spin_wheel_rewards_id'), table_name='spin_wheel_rewards')
    op.drop_table('spin_wheel_rewards')
    op.drop_index(op.f('ix_spin_wheel_config_id'), table_name='spin_wheel_config')
    op.drop_table('spin_wheel_config')
    # ### end Alembic commands ###
