"""initial tables

Revision ID: 45d3a351dc08
Revises: 9365634deb55
Create Date: 2026-01-23 14:46:30.188442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d3a351dc08'
down_revision: Union[str, Sequence[str], None] = '9365634deb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_suspended', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_suspended')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
