"""initial tables

Revision ID: 4885ba46f7ff
Revises: 2caeb196cfc7
Create Date: 2026-02-05 18:29:36.309487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4885ba46f7ff'
down_revision: Union[str, Sequence[str], None] = '2caeb196cfc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_codes_code'), 'gift_codes', ['code'], unique=True)
    op.create_index(op.f('ix_gift_codes_id'), 'gift_codes', ['id'], unique=False)
    op.create_table('gift_code_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gift_code_id', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('amount_claimed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gift_code_id'], ['gift_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gift_code_id', name='_user_giftcode_uc')
    )
    op.create_index(op.f('ix_gift_code_redemptions_id'), 'gift_code_redemptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_code_redemptions_id'), table_name='gift_code_redemptions')
    op.drop_table('gift_code_redemptions')
    op.drop_index(op.f('ix_gift_codes_id'), table_name='gift_codes')
    op.drop_index(op.f('ix_gift_codes_code'), table_name='gift_codes')
    op.drop_table('gift_codes')
    # ### end Alembic commands ###
