"""initial tables

Revision ID: 501dfd98b111
Revises: dc9e132cb66d
Create Date: 2026-01-30 16:32:26.705541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501dfd98b111'
down_revision: Union[str, Sequence[str], None] = 'dc9e132cb66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_wealthfunds', sa.Column('image', sa.String(), nullable=True))
    op.add_column('user_wealthfunds', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('user_wealthfunds', sa.Column('profit_percent', sa.Float(), nullable=False))
    op.add_column('user_wealthfunds', sa.Column('total_profit', sa.Float(), nullable=True))
    op.add_column('user_wealthfunds', sa.Column('today_interest', sa.Float(), nullable=True))
    op.add_column('user_wealthfunds', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('user_wealthfunds', sa.Column('end_date', sa.DateTime(), nullable=False))
    op.add_column('user_wealthfunds', sa.Column('status', sa.String(), nullable=True))
    op.drop_constraint(op.f('user_wealthfunds_user_id_wealthfund_id_key'), 'user_wealthfunds', type_='unique')
    op.add_column('wealthfunds', sa.Column('image', sa.String(), nullable=True))
    op.add_column('wealthfunds', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('wealthfunds', sa.Column('profit_percent', sa.Float(), nullable=False))
    op.add_column('wealthfunds', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wealthfunds', 'created_at')
    op.drop_column('wealthfunds', 'profit_percent')
    op.drop_column('wealthfunds', 'amount')
    op.drop_column('wealthfunds', 'image')
    op.create_unique_constraint(op.f('user_wealthfunds_user_id_wealthfund_id_key'), 'user_wealthfunds', ['user_id', 'wealthfund_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_wealthfunds', 'status')
    op.drop_column('user_wealthfunds', 'end_date')
    op.drop_column('user_wealthfunds', 'start_date')
    op.drop_column('user_wealthfunds', 'today_interest')
    op.drop_column('user_wealthfunds', 'total_profit')
    op.drop_column('user_wealthfunds', 'profit_percent')
    op.drop_column('user_wealthfunds', 'amount')
    op.drop_column('user_wealthfunds', 'image')
    # ### end Alembic commands ###
