"""initial tables

Revision ID: 690fb9cadb68
Revises: 917f22801681
Create Date: 2026-02-06 10:22:57.820775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690fb9cadb68'
down_revision: Union[str, Sequence[str], None] = '917f22801681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_user_giftcode_uc'), 'gift_code_redemptions', type_='unique')
    op.create_unique_constraint('unique_user_giftcode', 'gift_code_redemptions', ['user_id', 'gift_code_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_giftcode', 'gift_code_redemptions', type_='unique')
    op.create_unique_constraint(op.f('_user_giftcode_uc'), 'gift_code_redemptions', ['user_id', 'gift_code_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
