"""initial tables

Revision ID: 69863d1b8b05
Revises: cd41d199ac08
Create Date: 2026-01-26 19:00:44.277030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69863d1b8b05'
down_revision: Union[str, Sequence[str], None] = 'cd41d199ac08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposits', 'status')
    # ### end Alembic commands ###
