"""initial tables

Revision ID: 6a887ef2ebb6
Revises: 120ed3140667
Create Date: 2026-01-25 15:58:52.263556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a887ef2ebb6'
down_revision: Union[str, Sequence[str], None] = '120ed3140667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deposits_user_id_fkey'), 'deposits', type_='foreignkey')
    op.create_foreign_key(None, 'deposits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_level_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_levels_level_id_fkey'), 'user_levels', type_='foreignkey')
    op.drop_constraint(op.f('user_levels_user_id_fkey'), 'user_levels', type_='foreignkey')
    op.create_foreign_key(None, 'user_levels', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_levels', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_tasks_user_id_fkey'), 'user_tasks', type_='foreignkey')
    op.drop_constraint(op.f('user_tasks_task_id_fkey'), 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_tasks_completed_task_id_fkey'), 'user_tasks_completed', type_='foreignkey')
    op.drop_constraint(op.f('user_tasks_completed_user_id_fkey'), 'user_tasks_completed', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks_completed', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks_completed', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_tasks_pending_user_id_fkey'), 'user_tasks_pending', type_='foreignkey')
    op.drop_constraint(op.f('user_tasks_pending_task_id_fkey'), 'user_tasks_pending', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks_pending', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks_pending', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_wealthfunds_wealthfund_id_fkey'), 'user_wealthfunds', type_='foreignkey')
    op.drop_constraint(op.f('user_wealthfunds_user_id_fkey'), 'user_wealthfunds', type_='foreignkey')
    op.create_foreign_key(None, 'user_wealthfunds', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_wealthfunds', 'wealthfunds', ['wealthfund_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'referred_by',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    op.drop_constraint(op.f('wallets_user_id_fkey'), 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('withdrawals_user_id_fkey'), 'withdrawals', type_='foreignkey')
    op.create_foreign_key(None, 'withdrawals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.create_foreign_key(op.f('withdrawals_user_id_fkey'), 'withdrawals', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key(op.f('wallets_user_id_fkey'), 'wallets', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'referred_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'user_wealthfunds', type_='foreignkey')
    op.drop_constraint(None, 'user_wealthfunds', type_='foreignkey')
    op.create_foreign_key(op.f('user_wealthfunds_user_id_fkey'), 'user_wealthfunds', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_wealthfunds_wealthfund_id_fkey'), 'user_wealthfunds', 'wealthfunds', ['wealthfund_id'], ['id'])
    op.drop_constraint(None, 'user_tasks_pending', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks_pending', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_pending_task_id_fkey'), 'user_tasks_pending', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('user_tasks_pending_user_id_fkey'), 'user_tasks_pending', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_tasks_completed', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks_completed', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_completed_user_id_fkey'), 'user_tasks_completed', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_tasks_completed_task_id_fkey'), 'user_tasks_completed', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_task_id_fkey'), 'user_tasks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('user_tasks_user_id_fkey'), 'user_tasks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_levels', type_='foreignkey')
    op.drop_constraint(None, 'user_levels', type_='foreignkey')
    op.create_foreign_key(op.f('user_levels_user_id_fkey'), 'user_levels', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_levels_level_id_fkey'), 'user_levels', 'levels', ['level_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_level_id_fkey'), 'tasks', 'levels', ['level_id'], ['id'])
    op.drop_constraint(None, 'deposits', type_='foreignkey')
    op.create_foreign_key(op.f('deposits_user_id_fkey'), 'deposits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
