"""initial tables

Revision ID: 7da1342e0f11
Revises: 026606a4d6b7
Create Date: 2026-01-27 20:29:35.549382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da1342e0f11'
down_revision: Union[str, Sequence[str], None] = '026606a4d6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('tax', sa.Float(), nullable=False))
    op.add_column('withdrawals', sa.Column('net_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'net_amount')
    op.drop_column('withdrawals', 'tax')
    # ### end Alembic commands ###
