"""initial tables

Revision ID: 86b9b738e811
Revises: 0c4a2fa7ccbf
Create Date: 2026-01-26 09:59:09.791555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b9b738e811'
down_revision: Union[str, Sequence[str], None] = '0c4a2fa7ccbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'referred_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_referred_by_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_referred_by_fkey'), 'users', 'users', ['referred_by'], ['id'])
    op.alter_column('users', 'referred_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
