"""initial tables

Revision ID: 8b33504d5554
Revises: 4c96ad42fe48
Create Date: 2026-01-26 15:24:44.822008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b33504d5554'
down_revision: Union[str, Sequence[str], None] = '4c96ad42fe48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deposits_user_id_fkey'), 'deposits', type_='foreignkey')
    op.create_foreign_key(None, 'deposits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'levels', ['name'])
    op.drop_constraint(op.f('tasks_level_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'completed')
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'user_levels', ['user_id', 'level_id'])
    op.drop_constraint(op.f('user_levels_user_id_fkey'), 'user_levels', type_='foreignkey')
    op.drop_constraint(op.f('user_levels_level_id_fkey'), 'user_levels', type_='foreignkey')
    op.create_foreign_key(None, 'user_levels', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_levels', 'levels', ['level_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'user_tasks', ['user_id', 'task_id'])
    op.drop_constraint(op.f('user_tasks_task_id_fkey'), 'user_tasks', type_='foreignkey')
    op.drop_constraint(op.f('user_tasks_user_id_fkey'), 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_tasks_completed', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_tasks_completed', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'user_tasks_completed', ['user_id', 'task_id'])
    op.drop_constraint(op.f('user_tasks_completed_task_id_fkey'), 'user_tasks_completed', type_='foreignkey')
    op.drop_constraint(op.f('user_tasks_completed_user_id_fkey'), 'user_tasks_completed', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks_completed', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks_completed', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_tasks_pending', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_tasks_pending', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'user_tasks_pending', ['user_id', 'task_id'])
    op.drop_constraint(op.f('user_tasks_pending_user_id_fkey'), 'user_tasks_pending', type_='foreignkey')
    op.drop_constraint(op.f('user_tasks_pending_task_id_fkey'), 'user_tasks_pending', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks_pending', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_tasks_pending', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_wealthfunds', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user_wealthfunds', ['user_id', 'wealthfund_id'])
    op.drop_constraint(op.f('user_wealthfunds_user_id_fkey'), 'user_wealthfunds', type_='foreignkey')
    op.drop_constraint(op.f('user_wealthfunds_wealthfund_id_fkey'), 'user_wealthfunds', type_='foreignkey')
    op.create_foreign_key(None, 'user_wealthfunds', 'wealthfunds', ['wealthfund_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_wealthfunds', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('users_number_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_referral_code_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_number'), 'users', ['number'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.drop_constraint(op.f('users_referred_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'], ondelete='SET NULL')
    op.alter_column('wallets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('wallets_user_id_fkey'), 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'wealthfunds', ['name'])
    op.drop_constraint(op.f('withdrawals_user_id_fkey'), 'withdrawals', type_='foreignkey')
    op.create_foreign_key(None, 'withdrawals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'withdrawals', type_='foreignkey')
    op.create_foreign_key(op.f('withdrawals_user_id_fkey'), 'withdrawals', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'wealthfunds', type_='unique')
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key(op.f('wallets_user_id_fkey'), 'wallets', 'users', ['user_id'], ['id'])
    op.alter_column('wallets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_referred_by_fkey'), 'users', 'users', ['referred_by'], ['id'])
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_number'), table_name='users')
    op.create_unique_constraint(op.f('users_referral_code_key'), 'users', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_number_key'), 'users', ['number'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'user_wealthfunds', type_='foreignkey')
    op.drop_constraint(None, 'user_wealthfunds', type_='foreignkey')
    op.create_foreign_key(op.f('user_wealthfunds_wealthfund_id_fkey'), 'user_wealthfunds', 'wealthfunds', ['wealthfund_id'], ['id'])
    op.create_foreign_key(op.f('user_wealthfunds_user_id_fkey'), 'user_wealthfunds', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_wealthfunds', type_='unique')
    op.drop_column('user_wealthfunds', 'created_at')
    op.drop_constraint(None, 'user_tasks_pending', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks_pending', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_pending_task_id_fkey'), 'user_tasks_pending', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('user_tasks_pending_user_id_fkey'), 'user_tasks_pending', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_tasks_pending', type_='unique')
    op.alter_column('user_tasks_pending', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_tasks_pending', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'user_tasks_completed', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks_completed', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_completed_user_id_fkey'), 'user_tasks_completed', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_tasks_completed_task_id_fkey'), 'user_tasks_completed', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'user_tasks_completed', type_='unique')
    op.alter_column('user_tasks_completed', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_tasks_completed', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_user_id_fkey'), 'user_tasks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_tasks_task_id_fkey'), 'user_tasks', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'user_tasks', type_='unique')
    op.drop_constraint(None, 'user_levels', type_='foreignkey')
    op.drop_constraint(None, 'user_levels', type_='foreignkey')
    op.create_foreign_key(op.f('user_levels_level_id_fkey'), 'user_levels', 'levels', ['level_id'], ['id'])
    op.create_foreign_key(op.f('user_levels_user_id_fkey'), 'user_levels', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_levels', type_='unique')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_level_id_fkey'), 'tasks', 'levels', ['level_id'], ['id'])
    op.drop_constraint(None, 'levels', type_='unique')
    op.drop_constraint(None, 'deposits', type_='foreignkey')
    op.create_foreign_key(op.f('deposits_user_id_fkey'), 'deposits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
