"""initial tables

Revision ID: 9365634deb55
Revises: 1fb9e310f21f
Create Date: 2026-01-23 14:31:18.198891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9365634deb55'
down_revision: Union[str, Sequence[str], None] = '1fb9e310f21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
