"""initial tables

Revision ID: 9fe7704ed7e0
Revises: adcc85f5a845
Create Date: 2026-01-28 16:49:23.000547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe7704ed7e0'
down_revision: Union[str, Sequence[str], None] = 'adcc85f5a845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'locked')
    # ### end Alembic commands ###
