"""initial tables

Revision ID: adcc85f5a845
Revises: 7da1342e0f11
Create Date: 2026-01-28 15:23:16.537472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adcc85f5a845'
down_revision: Union[str, Sequence[str], None] = '7da1342e0f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('description', sa.String(), nullable=True))
    op.add_column('user_levels', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_levels', 'description')
    op.drop_column('levels', 'description')
    # ### end Alembic commands ###
