"""initial tables

Revision ID: c11105925a89
Revises: c76ec16683ec
Create Date: 2026-02-01 11:52:34.838114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11105925a89'
down_revision: Union[str, Sequence[str], None] = 'c76ec16683ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('referrals', sa.Column('bonus_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referrals', 'bonus_amount')
    op.drop_column('referrals', 'is_active')
    # ### end Alembic commands ###
