"""initial tables

Revision ID: c76ec16683ec
Revises: c93fbc20dd32
Create Date: 2026-02-01 11:42:55.220672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c76ec16683ec'
down_revision: Union[str, Sequence[str], None] = 'c93fbc20dd32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_bonuses_id'), table_name='referral_bonuses')
    op.drop_table('referral_bonuses')
    op.add_column('referrals', sa.Column('level', sa.String(), nullable=False))
    op.drop_constraint(op.f('referrals_referrer_id_referred_id_key'), 'referrals', type_='unique')
    op.create_unique_constraint('_referrer_referred_uc', 'referrals', ['referrer_id', 'referred_id'])
    op.drop_constraint(op.f('referrals_level_id_fkey'), 'referrals', type_='foreignkey')
    op.drop_column('referrals', 'active_level_at')
    op.drop_column('referrals', 'level_id')
    op.drop_column('referrals', 'is_active')
    op.drop_column('users', 'total_referrals')
    op.drop_column('users', 'active_referrals')
    op.drop_column('wallets', 'referral_earnings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('referral_earnings', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('active_referrals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_referrals', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('active_level_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('referrals_level_id_fkey'), 'referrals', 'levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('_referrer_referred_uc', 'referrals', type_='unique')
    op.create_unique_constraint(op.f('referrals_referrer_id_referred_id_key'), 'referrals', ['referrer_id', 'referred_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('referrals', 'level')
    op.create_table('referral_bonuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('referral_bonuses_referral_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('referral_bonuses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_bonuses_pkey'))
    )
    op.create_index(op.f('ix_referral_bonuses_id'), 'referral_bonuses', ['id'], unique=False)
    # ### end Alembic commands ###
