"""initial tables

Revision ID: cd41d199ac08
Revises: 8b33504d5554
Create Date: 2026-01-26 18:56:59.289309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd41d199ac08'
down_revision: Union[str, Sequence[str], None] = '8b33504d5554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('name', sa.String(), nullable=False))
    op.add_column('deposits', sa.Column('number', sa.String(), nullable=False))
    op.add_column('deposits', sa.Column('account_number', sa.String(), nullable=True))
    op.add_column('deposits', sa.Column('payment_method', sa.String(), nullable=False))
    op.add_column('deposits', sa.Column('message', sa.String(), nullable=True))
    op.alter_column('deposits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deposits', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('deposits', 'message')
    op.drop_column('deposits', 'payment_method')
    op.drop_column('deposits', 'account_number')
    op.drop_column('deposits', 'number')
    op.drop_column('deposits', 'name')
    # ### end Alembic commands ###
